// <auto-generated />
namespace UniSocial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201710170640325_DbChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
